### PR TITLE
Rename package to @synonymdev/react-native-keychain to publish it to npm

### PR DESCRIPTION
**Pull request by limpbrains**
We need to publish this package to npm.
So I'm renaming it and also I think current master should reflect the state of it in npm, so I'm adding all the patches by @ovitrif

### CODE REVIEW

**Comment by limpbrains** [comment]
@ovitrif please take a look

**Comment by ovitrif** [comment]
@limpbrains all good

**Comment by limpbrains** [comment]
please approve and merge, I have no rights

**Comment by ovitrif** [comment]
@limpbrains Did you also merge/update with `master` of the `react-native-keychain` repo?

**Review by ovitrif — APPROVED** [review]

**Comment by ovitrif** [comment]
Approved but it seems I also don't have rights lol, need admin rights from @BitcoinErrorLog

**Comment by limpbrains** [comment]
> @limpbrains Did you also merge/update with `master` of the `react-native-keychain` repo?

I did not, just used your branch

**Comment by ovitrif** [comment]
@limpbrains PR is now merged, ~~I'll see to it that we merge with master from [`oblador/react-native-keychain`](https://github.com/oblador/react-native-keychain)~~

Perhaps not a good idea, we should rather sync it with the stable version of the root repo.

**Pull request merged**
